name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SCALACTIC_FILL_FILE_PATHNAMES: true
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Compile
      run: sbt -J-Xmx3G -J-Xss5M compile
      
    - name: Test
      run: sbt -J-Xmx3G -J-Xss5M test
      
    - name: Package
      run: sbt dist/stage
    
